#define computeSpanningTree_IMPLEMENTED
#define computeTreeFunctions_IMPLEMENTED
#define createAuxiliaryGraph_IMPLEMENTED
#define computeConnectedComponents_IMPLEMENTED
#define extendRelation_IMPLEMENTED
#define computeBiconnectedComponents_IMPLEMENTED
